### ISSUE TITLE
Broken css

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox-dash-ui-usage-breakdown#1]
Looks like some css broke:

![image](https://cloud.githubusercontent.com/assets/181484/24069013/c42e373e-0b62-11e7-8c21-46aa996ec3a3.png)

**Comment by jedgalbraith** [comment]
@sanderson Is this still an issue? I'm not seeing it.

**Comment by sanderson** [comment]
Yes, I'm still seeing it.

**Comment by jedgalbraith** [comment]
@sanderson Can you provide more details? Is it a specific app, browser, etc? I can't reproduce.

**Comment by sanderson** [comment]
Its on the app 'content'. I'm using Chrome Version 57.0.2987.98.

**Comment by jedgalbraith** [comment]
I just upgraded from Chrome Version 56.0.2924.87 to 57.0.2987.133 and now I see it.

@Tolmark12 Can you take a look at this?
e.g. https://dashboard.nanobox.io/apps/content > do.1 > Stats

**Comment by Tolmark12** [comment]
@sdomino, sounds like a new chrome update broke something, want to check it out?

**Comment by jedgalbraith** [comment]
fixed & deployed.
![screen shot 2017-04-07 at 10 43 11 am](https://cloud.githubusercontent.com/assets/313947/24810529/bf64ddc0-1b7f-11e7-85fc-13a166afde96.png)
